name: "Google Chat Notification Action"
description: "GitHub action to send highly customizable card V2 notifications to a google chat via webhook."
author: "Simon Scholz"

runs:
  using: node20
  main: dist/index.js

branding:
  icon: 'message-circle'
  color: 'blue'

inputs:
  webhookUrl :
    description: 'The webhook url of the google chat. Should be stored in an action secret.'
    required: true
  jobStatus:
    description: 'The optional jobStatus. Values can be success, failure, cancelled. You should pass job.status variable here.'
    required: false
  title:
    description: 'Optional title. If not set it defaults to the action name.'
    required: false
  subtitle:
    description: 'Optional subtitle. If not set the subtitle will not be shown.'
    required: false
  imageUrl:
    description: 'Optional icon. If not set no icon will be shown.'
    required: false
  imageType:
    description: 'Optional imageType (imageUrl must be set for this). Possible values are SQUARE and CIRCLE. If not set this will default to CIRCLE'
    required: false
  imageAltText:
    description: 'Optional imageAltText. Alternative in case the image cannot be shown.'
    required: false
  createDefaultSection:
    description: 'Optional createDefaultSection. Specify whether the default section should be shown or not.'
    required: false
    default: 'true'
  collapsibleDefaultSection:
    description: 'Optional collapsibleSection. Specify whether the section is collapsible.'
    required: false
    default: 'true'
  uncollapsibleWidgetsCount:
    description: 'Optional uncollapsibleWidgetsCount. Specify the amount of uncollapsible widgets within the sections.'
    required: false
    default: '4'
  additionalButtons:
    description: 'Add the opportunity to have additional buttons.'
    required: false
    default: '[]'
  additionalSections:
    description: 'Add the opportunity to have additional sections.'
    required: false
    default: '[]'
  threadName:
    description: 'Reply to a thread identified by this value. See https://developers.google.com/chat/api/reference/rest/v1/spaces.messages#Thread for more information'
    required: false
  threadKey:
    description: 'Create or reply to a thread identified by this value. For replying to a thread this message must be sent by the same Google Chat user as the initial message.'
    required: false

outputs:
  threadName:
    description: 'Name of thread created by this message. Can be used as input "threadName" for subsequent calls to this action to have follow-up messages in a thread.'
